[project]
name = "multiagent-trading-framework"
version = "1.0.0"
description = "AI-native multi-agent trading framework"
authors = [{name="Sandro"}]
license = "MIT"
dependencies = [
    "ccxt",
    "pandas",
    "numpy",
    "matplotlib",
    "pyyaml",
    "streamlit",
    "sphinx",
    "sphinx-rtd-theme",
    "scikit-learn",
    "scipy",
    "fastapi",
    "uvicorn",
    "pydantic",
    "requests",
    "plotly",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
