[project]
name = "multiagent-trading-framework"
version = "0.5.0"
description = "AI-native multi-agent trading framework"
authors = [{name="Sandro"}]
license = "MIT"
dependencies = [
    "ccxt",
    "pandas",
    "numpy",
    "matplotlib",
    "pyyaml",
    "streamlit",
    "sphinx",
    "sphinx-rtd-theme",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
